# .gitpod.yml
image:
  file: .gitpod.Dockerfile

# Rest of the configuration remains the same
tasks:
  - name: Setup Environment
    init: |
      go mod tidy
    command: |
      go run main.go

# ports:
#   - port: 8080
#     onOpen: open-preview
#   - port: 3000
#     onOpen: open-preview

vscode:
  extensions:
    - golang.Go
    - ms-vscode.go-nightly
    - streetsidesoftware.code-spell-checker
    - humao.rest-client

env:
  MIRROR_NODE_API_URL: "https://mainnet.mirrornode.hedera.com/api/v1"

after:
  - echo "Workspace setup complete."
